# Generated by Django 2.1.4 on 2018-12-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='hire_Date',
            new_name='hire_date',
        ),
    ]
